# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Synvert
tagline:          'syntax + convert'
description:      'write snippet code to rewrite your source code.'
url:              https://synvert.net

author:
  name:           'Xinmin Labs'
  url:            https://xinminlabs.com

plugins:
  - jekyll-redirect-from

exclude:
  - Gemfile*
  - README.md
  - deploy.sh
  - Dockerfile.prod
  - docker-nginx.conf
  - sync_snippets.rb
