# Dependencies
markdown:         kramdown
highlighter:      rouge
kramdown:
  input: GFM

# Permalinks
permalink:        pretty

# Setup
title:            Synvert
tagline:          'syntax + convert'
description:      'write snippet code to rewrite your source code.'
url:              https://synvert.net

author:
  name:           'Richard Huang'
  url:            https://huangzhimin.com

plugins:
  - jekyll-redirect-from
  - jekyll-compress-images

exclude:
  - Gemfile*
  - README.md
  - deploy.sh
  - Dockerfile.prod
  - docker-nginx.conf
  - _compress_images_cache.yml
