# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Synvert
tagline:          'syntax + convert'
description:      'write ruby code to change ruby code.'
url:              https://synvert.xinminlabs.com

author:
  name:           'Xinmin Labs'
  url:            https://xinminlabs.com

plugins:
  - jekyll-redirect-from
