# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:categories/:title

# Setup
title:            Synvert
tagline:          'syntax + convert'
description:      'write code to change code.'
url:              https://synvert.xinminlabs.com

author:
  name:           'Xinmin Labs'
  url:            https://xinminlabs.com

plugins:
  - jekyll-redirect-from
